import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';

import Navbar from './components/Navbar';
import Hero from './components/Hero';
import Card from './components/Card';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id='container'>
        <div id="wrapper">
          <Navbar />
          <Hero />
          <Card 
            img="katie-zaferes.png"
            rating="5.0"
            reviewCount={6}
            country="Norway"
            title="Life Lessons with Katie Zaferes"
            price={136}
          />

        </div>
      </div>
    </>
  )
}

/*
Challenge: Pass props to the Card component and display that data

img="katie-zaferes.png"
rating="5.0"
reviewCount={6}
country="Norway"
title="Life Lessons with Katie Zaferes"
price={136}

*/