import Head from 'next/head'
import Die from './Die'
import { useState, useEffect, use } from 'react'

export default function Home() {
  const allNewDice = () => {
    return Array.from({length: 10}, () => Math.floor(Math.random() * 6) + 1);
  }
  const [dice, setDice] = useState([])

  useEffect(() => setDice(() => allNewDice()), [])

  const diceElements = dice.map(num => <Die value={num} />)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container'>
        <div className='dies'>
          {diceElements}
        </div>
      </main>
    </>
  )
}
